baseURL = 'http://zediogoviana.github.io/'
languageCode = 'en-us'
title = 'zediogoviana does things'
theme = 'terminal'

paginate = 5

[params]
  # dir name of your main content (default is `content/posts`).
  # the list of set content will show up on your index page (baseurl).
  contentTypeName = "posts"

  # ["orange", "blue", "red", "green", "pink"]
  themeColor = "blue"

  # if you set this to 0, only submenu trigger will be visible
  showMenuItems = 6

  # show selector to switch language
  showLanguageSelector = false

  # set theme to full screen width
  fullWidthTheme = false

  # center theme with default width
  centerTheme = true

  # if your resource directory contains an image called `cover.(jpg|png|webp)`,
  # then the file will be used as a cover automatically.
  # With this option you don't have to put the `cover` param in a front-matter.
  autoCover = true

  # set post to show the last updated
  # If you use git, you can set `enableGitInfo` to `true` and then post will automatically get the last updated
  showLastUpdated = false

  # set a custom favicon (default is a `themeColor` square)
  favicon = "img/duck.ico"

  # Provide a string as a prefix for the last update date. By default, it looks like this: 2020-xx-xx [Updated: 2020-xx-xx] :: Author
  # updatedDatePrefix = "Updated"

  # set all headings to their default size (depending on browser settings)
  # oneHeadingSize = true # default

  # whether to show a page's estimated reading time
  # readingTime = false # default

  # whether to show a table of contents
  # can be overridden in a page's front-matter
  # Toc = false # default

  # set title for the table of contents
  # can be overridden in a page's front-matter
  # TocTitle = "Table of Contents" # default


[params.twitter]
  # set Twitter handles for Twitter cards
  # see https://developer.twitter.com/en/docs/tweets/optimize-with-cards/guides/getting-started#card-and-content-attribution
  # do not include @
  creator = "zediogoviana"
  site = "https://zediogoviana.github.io/"

[languages]
  [languages.en]
    languageName = "English"
    title = "zediogoviana"
    subtitle = """
      My name is JosÃ© Diogo Viana, but everyone calls me /(ZÃ©|Diogo)/.
      In this place you can find posts about random things I explored either in my free time or during my random discoveries at finiam.
      Look around the post list or other website pages to know a bit more about what I do: ðŸ‘¨ðŸ¼â€ðŸ’»ðŸºâš½ï¸
    """
    owner = "zediogoviana"
    keywords = ["personal website", "development", "football", "beers", "zediogoviana"]
    copyright = ""
    menuMore = "Show more"
    readMore = "Read more"
    readOtherPosts = "Read other posts"
    newerPosts = "Newer posts"
    olderPosts = "Older posts"
    missingContentMessage = "Oh no! This page doesn't exist... "
    missingBackButtonLabel = "Back to home page"
    minuteReadingTime = "min read"
    words = "words"

    [languages.en.params.logo]
      logoText = "zediogoviana"
      logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
      [[languages.en.menu.main]]
        identifier = "locations"
        name = "Locations"
        url = "/locations"
      [[languages.en.menu.main]]
        identifier = "projects"
        name = "Side Projects"
        url = "/projects"
      [[languages.en.menu.main]]
        identifier = "football"
        name = "Football"
        url = "/football"
      [[languages.en.menu.main]]
        identifier = "posts"
        name = "Post List"
        url = "/posts"
      [[languages.en.menu.main]]
        identifier = "other-media"
        name = "Other Media"
        url = "/other-media"

# [module]
#   # In case you would like to make changes to the theme and keep it locally in you repository,
#   # uncomment the line below (and correct the local path if necessary).
#   # --
#   # replacements = "github.com/panr/hugo-theme-terminal -> themes/terminal"
# [[module.imports]]
#   path = 'github.com/panr/hugo-theme-terminal'
